<?xml version="1.0" encoding="utf-8"?><Database Name="DevelopmentDB" Class="HRDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=DevelopmentDB;Integrated Security=True" SettingsObjectName="NCommon.LinqToSql.Tests.HRDomain.Properties.Settings" SettingsPropertyName="DevelopmentDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SalesPerson" Member="SalesPersons">
    <Type Name="SalesPerson">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SalesQuota" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="SalesYTD" Type="System.Decimal" DbType="Decimal(19,5)" CanBeNull="true" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TerritoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Department_SalesPerson" Member="Department" ThisKey="DepartmentId" OtherKey="Id" Type="Department" IsForeignKey="true" />
      <Association Name="SalesTerritory_SalesPerson" Member="SalesTerritory" ThisKey="TerritoryId" OtherKey="Id" Type="SalesTerritory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Departments" Member="Departments">
    <Type Name="Department">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Department_SalesPerson" Member="SalesPersons" ThisKey="Id" OtherKey="DepartmentId" Type="SalesPerson" />
    </Type>
  </Table>
  <Table Name="dbo.SalesTerritory" Member="SalesTerritories">
    <Type Name="SalesTerritory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="SalesTerritory_SalesPerson" Member="SalesPersons" ThisKey="Id" OtherKey="TerritoryId" Type="SalesPerson" />
    </Type>
  </Table>
</Database>